-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PROPRIETARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROPRIETARIOS` (
  `CPF` VARCHAR(14) NOT NULL,
  `NOME` VARCHAR(100) NOT NULL,
  `TELEFONE` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(60) NOT NULL,
  `DT_NASCIMENTO` DATE NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GESTAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GESTAO` (
  `ID_GESTAO` INT NOT NULL,
  `DT_INICIO` DATE NOT NULL,
  `DT_FIM` DATE NOT NULL,
  `ATOS` TEXT(500) NULL,
  `ESTATUTO` BLOB NULL,
  `CPF_SINDICO` VARCHAR(14) NOT NULL,
  `CPF_SUBSINDICO` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`ID_GESTAO`, `CPF_SINDICO`, `CPF_SUBSINDICO`),
  INDEX `fk_GESTAO_PROPRIETARIOS_idx` (`CPF_SINDICO` ASC) VISIBLE,
  INDEX `fk_GESTAO_PROPRIETARIOS1_idx` (`CPF_SUBSINDICO` ASC) VISIBLE,
  CONSTRAINT `fk_GESTAO_PROPRIETARIOS`
    FOREIGN KEY (`CPF_SINDICO`)
    REFERENCES `mydb`.`PROPRIETARIOS` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GESTAO_PROPRIETARIOS1`
    FOREIGN KEY (`CPF_SUBSINDICO`)
    REFERENCES `mydb`.`PROPRIETARIOS` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UNIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UNIDADES` (
  `ID_UNIDADE` INT NOT NULL,
  `CPF_PROPRIETARIO` VARCHAR(14) NOT NULL,
  `BLOCO` VARCHAR(5) NOT NULL,
  `NUMERO` VARCHAR(10) NOT NULL,
  `NUM_VAGA` VARCHAR(10) NOT NULL,
  `PLACA_VEICULO` VARCHAR(8) NULL,
  PRIMARY KEY (`ID_UNIDADE`, `CPF_PROPRIETARIO`),
  INDEX `fk_UNIDADES_PROPRIETARIOS1_idx` (`CPF_PROPRIETARIO` ASC) VISIBLE,
  CONSTRAINT `fk_UNIDADES_PROPRIETARIOS1`
    FOREIGN KEY (`CPF_PROPRIETARIO`)
    REFERENCES `mydb`.`PROPRIETARIOS` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REUNIOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REUNIOES` (
  `ID_REUNIAO` INT NOT NULL,
  `ID_GESTAO` INT NOT NULL,
  `TITULO` VARCHAR(50) NOT NULL,
  `LOCAL` VARCHAR(45) NOT NULL,
  `DATA` DATE NOT NULL,
  `HORARIO` TIME NOT NULL,
  `PAUTA` TEXT(300) NOT NULL,
  `ATA` BLOB NULL,
  PRIMARY KEY (`ID_REUNIAO`, `ID_GESTAO`),
  INDEX `fk_REUNIOES_GESTAO1_idx` (`ID_GESTAO` ASC) VISIBLE,
  CONSTRAINT `fk_REUNIOES_GESTAO1`
    FOREIGN KEY (`ID_GESTAO`)
    REFERENCES `mydb`.`GESTAO` (`ID_GESTAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESENCA_REUNIAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRESENCA_REUNIAO` (
  `ID_UNIDADE` INT NOT NULL,
  `ID_REUNIAO` INT NOT NULL,
  `NOME` VARCHAR(60) NOT NULL,
  `OBS` TEXT(100) NULL,
  PRIMARY KEY (`ID_UNIDADE`, `ID_REUNIAO`),
  INDEX `fk_UNIDADES_has_REUNIOES_REUNIOES1_idx` (`ID_REUNIAO` ASC) VISIBLE,
  INDEX `fk_UNIDADES_has_REUNIOES_UNIDADES1_idx` (`ID_UNIDADE` ASC) VISIBLE,
  CONSTRAINT `fk_UNIDADES_has_REUNIOES_UNIDADES1`
    FOREIGN KEY (`ID_UNIDADE`)
    REFERENCES `mydb`.`UNIDADES` (`ID_UNIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UNIDADES_has_REUNIOES_REUNIOES1`
    FOREIGN KEY (`ID_REUNIAO`)
    REFERENCES `mydb`.`REUNIOES` (`ID_REUNIAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AREAS_COMUNS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AREAS_COMUNS` (
  `ID_AREA` INT NOT NULL,
  `NOME` VARCHAR(60) NOT NULL,
  `REGRAS` TEXT(200) NOT NULL,
  `CAPACIDADE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_AREA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OCORRENCIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OCORRENCIAS` (
  `ID_OCORRENCIA` INT NOT NULL AUTO_INCREMENT,
  `ID_UNIDADE` INT NOT NULL,
  `ID_AREA` INT NOT NULL,
  `ID_GESTAO` INT NOT NULL,
  `TITULO` VARCHAR(70) NOT NULL,
  `DESCRICAO` TEXT(300) NOT NULL,
  `NOME` VARCHAR(60) NOT NULL,
  `DT_HORA` DATETIME NOT NULL,
  `ARQUIVO` LONGBLOB NULL,
  `ACAO_TOMADA` TEXT(200) NULL,
  `STATUS` TINYINT NULL,
  PRIMARY KEY (`ID_OCORRENCIA`, `ID_UNIDADE`, `ID_AREA`, `ID_GESTAO`),
  INDEX `fk_OCORRENCIAS_UNIDADES1_idx` (`ID_UNIDADE` ASC) VISIBLE,
  INDEX `fk_OCORRENCIAS_GESTAO1_idx` (`ID_GESTAO` ASC) VISIBLE,
  INDEX `fk_OCORRENCIAS_AREAS_COMUNS1_idx` (`ID_AREA` ASC) VISIBLE,
  CONSTRAINT `fk_OCORRENCIAS_UNIDADES1`
    FOREIGN KEY (`ID_UNIDADE`)
    REFERENCES `mydb`.`UNIDADES` (`ID_UNIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OCORRENCIAS_GESTAO1`
    FOREIGN KEY (`ID_GESTAO`)
    REFERENCES `mydb`.`GESTAO` (`ID_GESTAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OCORRENCIAS_AREAS_COMUNS1`
    FOREIGN KEY (`ID_AREA`)
    REFERENCES `mydb`.`AREAS_COMUNS` (`ID_AREA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESERVAS` (
  `ID_RESERVA` INT NOT NULL AUTO_INCREMENT,
  `ID_UNIDADE` INT NOT NULL,
  `ID_AREA` INT NOT NULL,
  `NOME_RESP` VARCHAR(60) NOT NULL,
  `QTD_PESSOAS` VARCHAR(20) NOT NULL,
  `DESCRICAO` TEXT(100) NOT NULL,
  `DT_HORARIO` DATETIME NOT NULL,
  `DURACAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_RESERVA`, `ID_UNIDADE`, `ID_AREA`),
  INDEX `fk_RESERVAS_UNIDADES1_idx` (`ID_UNIDADE` ASC) VISIBLE,
  INDEX `fk_RESERVAS_AREAS_COMUNS1_idx` (`ID_AREA` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVAS_UNIDADES1`
    FOREIGN KEY (`ID_UNIDADE`)
    REFERENCES `mydb`.`UNIDADES` (`ID_UNIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVAS_AREAS_COMUNS1`
    FOREIGN KEY (`ID_AREA`)
    REFERENCES `mydb`.`AREAS_COMUNS` (`ID_AREA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_SERVICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_SERVICO` (
  `ID_TIPO` INT NOT NULL,
  `DESCRICAO` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID_TIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRAZOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRAZOS` (
  `ID_PRAZO` INT NOT NULL,
  `DATA_INICIO` DATE NOT NULL,
  `DATA_FIM` DATE NOT NULL,
  `PERIODICIDADE` VARCHAR(45) NOT NULL,
  `QTD_DIAS` INT NOT NULL,
  `DT_ULT_REALIZACAO` DATE NOT NULL,
  PRIMARY KEY (`ID_PRAZO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORNECEDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FORNECEDORES` (
  `CNPJ` VARCHAR(18) NOT NULL,
  `R_SOCIAL` VARCHAR(60) NOT NULL,
  `TELEFONE` VARCHAR(15) NOT NULL,
  `EMAIL` VARCHAR(70) NOT NULL,
  `ENDERECO` VARCHAR(100) NOT NULL,
  `CIDADE` VARCHAR(45) NOT NULL,
  `RESPONSAVEL` VARCHAR(80) NOT NULL,
  `TEL_RESP` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORCAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORCAMENTOS` (
  `ID_ORCAMENTO` INT NOT NULL,
  `CNPJ` VARCHAR(18) NOT NULL,
  `ID_PRAZO` INT NOT NULL,
  `ID_TIPO` INT NOT NULL,
  `DATA` DATE NOT NULL,
  `VALOR` DECIMAL NOT NULL,
  `DESCRICAO` TEXT(200) NOT NULL,
  PRIMARY KEY (`ID_ORCAMENTO`, `CNPJ`, `ID_PRAZO`, `ID_TIPO`),
  INDEX `fk_ORCAMENTOS_FORNECEDORES1_idx` (`CNPJ` ASC) VISIBLE,
  INDEX `fk_ORCAMENTOS_PRAZOS1_idx` (`ID_PRAZO` ASC) VISIBLE,
  INDEX `fk_ORCAMENTOS_TIPO_SERVICO1_idx` (`ID_TIPO` ASC) VISIBLE,
  CONSTRAINT `fk_ORCAMENTOS_FORNECEDORES1`
    FOREIGN KEY (`CNPJ`)
    REFERENCES `mydb`.`FORNECEDORES` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORCAMENTOS_PRAZOS1`
    FOREIGN KEY (`ID_PRAZO`)
    REFERENCES `mydb`.`PRAZOS` (`ID_PRAZO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORCAMENTOS_TIPO_SERVICO1`
    FOREIGN KEY (`ID_TIPO`)
    REFERENCES `mydb`.`TIPO_SERVICO` (`ID_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICOS` (
  `ID_SERVICO` INT NOT NULL,
  `ID_TIPO` INT NOT NULL,
  `ID_PRAZO` INT NOT NULL,
  `CNPJ` VARCHAR(18) NOT NULL,
  `ID_GESTAO` INT NOT NULL,
  `ID_ORCAMENTO` INT NOT NULL,
  `DT_PAG` DATE NOT NULL,
  `RESPONSAVEL` VARCHAR(60) NOT NULL,
  `OBS` TEXT(200) NULL,
  `CONTRATO` BLOB NULL,
  PRIMARY KEY (`ID_SERVICO`, `ID_TIPO`, `ID_PRAZO`, `CNPJ`, `ID_GESTAO`, `ID_ORCAMENTO`),
  INDEX `fk_SERVICOS_TIPO_SERVICO1_idx` (`ID_TIPO` ASC) VISIBLE,
  INDEX `fk_SERVICOS_PRAZOS1_idx` (`ID_PRAZO` ASC) VISIBLE,
  INDEX `fk_SERVICOS_FORNECEDORES1_idx` (`CNPJ` ASC) VISIBLE,
  INDEX `fk_SERVICOS_GESTAO1_idx` (`ID_GESTAO` ASC) VISIBLE,
  INDEX `fk_SERVICOS_ORCAMENTOS1_idx` (`ID_ORCAMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_SERVICOS_TIPO_SERVICO1`
    FOREIGN KEY (`ID_TIPO`)
    REFERENCES `mydb`.`TIPO_SERVICO` (`ID_TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICOS_PRAZOS1`
    FOREIGN KEY (`ID_PRAZO`)
    REFERENCES `mydb`.`PRAZOS` (`ID_PRAZO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICOS_FORNECEDORES1`
    FOREIGN KEY (`CNPJ`)
    REFERENCES `mydb`.`FORNECEDORES` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICOS_GESTAO1`
    FOREIGN KEY (`ID_GESTAO`)
    REFERENCES `mydb`.`GESTAO` (`ID_GESTAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICOS_ORCAMENTOS1`
    FOREIGN KEY (`ID_ORCAMENTO`)
    REFERENCES `mydb`.`ORCAMENTOS` (`ID_ORCAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVICOS_FEITOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SERVICOS_FEITOS` (
  `ID_SERVICO` INT NOT NULL,
  `ID_AREA` INT NOT NULL,
  PRIMARY KEY (`ID_SERVICO`, `ID_AREA`),
  INDEX `fk_SERVICOS_has_AREAS_COMUNS_AREAS_COMUNS1_idx` (`ID_AREA` ASC) VISIBLE,
  INDEX `fk_SERVICOS_has_AREAS_COMUNS_SERVICOS1_idx` (`ID_SERVICO` ASC) VISIBLE,
  CONSTRAINT `fk_SERVICOS_has_AREAS_COMUNS_SERVICOS1`
    FOREIGN KEY (`ID_SERVICO`)
    REFERENCES `mydb`.`SERVICOS` (`ID_SERVICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICOS_has_AREAS_COMUNS_AREAS_COMUNS1`
    FOREIGN KEY (`ID_AREA`)
    REFERENCES `mydb`.`AREAS_COMUNS` (`ID_AREA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
